include:
  - package:very_good_analysis/analysis_options.yaml
formatter:
  page_width: 120
analyzer:
  plugins:
    - custom_lint
  exclude:
    - lib/l10n/gen/*
    - "**/*.g.dart"
    - "**/*.freezed.dart"
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
